create database class2;
use class2;
CREATE TABLE customers (
    customer_id INT PRIMARY KEY,
    customer_name VARCHAR(100) NOT NULL,
    city VARCHAR(50),
    country VARCHAR(50),
    signup_date DATE
);
select * from customers;

CREATE TABLE products (
    product_id INT PRIMARY KEY,
    product_name VARCHAR(100) NOT NULL,
    category VARCHAR(50),
    price DECIMAL(10,2) NOT NULL,
    stock INT DEFAULT 0
);
select * from products;

CREATE TABLE orders (
    order_id INT PRIMARY KEY,
    customer_id INT NOT NULL,
    order_date DATE NOT NULL,
    status VARCHAR(30),
    payment_method VARCHAR(30),

    FOREIGN KEY (customer_id)
    REFERENCES customers(customer_id)
);
select * from orders;

CREATE TABLE order_items (
    order_item_id INT PRIMARY KEY,
    order_id INT NOT NULL,
    product_id INT NOT NULL,
    quantity INT NOT NULL,
    unit_price DECIMAL(10,2) NOT NULL,

    FOREIGN KEY (order_id)
    REFERENCES orders(order_id),

    FOREIGN KEY (product_id)
    REFERENCES products(product_id)
);
select * from order_items;

-- Q1. Show all customers from Bengaluru.
select * from customers
where city = 'Bengaluru';

-- Q2. Show customers who signed up after ‘2025-01-01’.
select * from customers
where signup_date > '2025-01-01';

-- Q3. Find customers from Mumbai and Hyderabad.
select * from customers
where city in ( 'Mumbai','Hyderabad');

-- Q4. Show products belonging to the Electronics category.
select * from products
where category = 'Electronics';

-- Q5. Find products priced above 40000.
select * from products
where price > 40000;

-- Q6. Show products where stock is less than 20.
select * from products
where stock < 20 ;

-- Q7. Find products with stock between 50 and 100.
select * from products
where stock between 50 and 100;

-- Q8. Show customers whose names start with ‘A’.
select * from customers
where customer_name like 'A%';

-- Q9. Find products whose names contain ‘Premium’.
select * from products
where product_name like 'Premium%';

-- Q10. Show customers registered during the year 2025.
select * from customers
where year(signup_date)= 2025;

--  Q11. Find total revenue generated by each category.
select * from products;
select category,sum(price) as Revenue
from products
group by category
order by revenue desc
limit 5 ;

-- Q12. Find total quantity sold for each product.
SELECT p.product_name,SUM(oi.quantity) AS total_quantity
FROM order_items AS oi
JOIN products AS p
ON oi.product_id = p.product_id
GROUP BY p.product_name;

-- Q13. Find total orders under each order status.
select status,count(order_id)  from orders
group by status;

-- Q14. Find total revenue generated through each payment method.

select o.payment_method,sum(p.price) as total_revenue
from orders as o
join order_items as oi
on o.order_id = oi.order_id
join products as p
on p.product_id=oi.product_id
group by o.payment_method
order by  total_revenue desc
limit 5;

-- Q15. Find average product price category-wise.
select category,avg(price) as avg_price from products
group by category;

-- Q16. Find category-wise quantity sold.
select p.category,sum(oi.quantity) as total_quantity
from order_items oi
join products p
on oi.product_id = p.product_id
group by p.category;

-- Q17. Find monthly order count.
select month(order_date) as month,count(*) as total_orders
from orders
group by month(order_date);

-- Q18. Find monthly revenue trend.
select month(o.order_date) as month,sum(oi.quantity * p.price) as revenue
from orders o
join order_items oi
on o.order_id = oi.order_id
join products p
on oi.product_id = p.product_id
group by month(o.order_date)
order by month;

-- Q19. Find the most commonly used payment method.
select payment_method from orders
group by payment_method
order by COUNT(*) DESC
LIMIT 1;

-- -- Q20. Find the highest revenue-generating category.
select p.category,SUM(p.price * oi.quantity) as total_revenue
from products p
inner join order_items oi
on p.product_id = oi.product_id
group by p.category
having SUM(p.price * oi.quantity) =(select MAX(category_revenue)
from(select SUM(p.price * oi.quantity) as category_revenue from products p
inner join order_items oi 
on p.product_id = oi.product_id
group by p.category) as revenue_table);

 -- Q21. Find customers who placed more than 5 orders.
 select customer_id,count(order_id) AS total_orders
from orders
group by customer_id
having count(order_id) > 5;


-- Q22. Find top 5 customers based on total spending.
select c.customer_name,
       sum(p.price * oi.quantity) as total_spending
from customers c
join orders o on c.customer_id = o.customer_id
join order_items oi on o.order_id = oi.order_id
join products p on oi.product_id = p.product_id
group by c.customer_name
order by total_spending desc
limit 5;

 --  Q23. Find products sold more than 30 times.
select p.product_name,sum(oi.quantity) AS total_sold
from order_items oi
join products p
on oi.product_id = p.product_id
group by p.product_name
having SUM(oi.quantity) > 30;

-- Q24. Find categories generating revenue greater than 500000.
select p.category,sum(oi.quantity * p.price) as revenue
from order_items oi
join products p
on oi.product_id = p.product_id
group by p.category
having revenue > 500000;

-- Q25. Find cities having more than 10 customers.
select city,count(customer_id) as total_customers
from customers
group by city
having count(customer_id) > 10;


-- Q26. Find the top 5 highest-selling products.
select p.product_name,sum(oi.quantity) as total_sold
from products p
join order_items oi
on p.product_id = oi.product_id
group by p.product_name
order by total_sold desc
limit 5;


-- Q27. Find the top 3 most profitable products.
select p.product_name,sum(p.price * oi.quantity) as profit
from products p
join order_items oi
on p.product_id = oi.product_id
group by p.product_name
order by profit desc
limit 3;


-- Q28. Find customers whose spending is above average customer spending.
select c.customer_name,sum(p.price * oi.quantity) as total_spending
from customers c
join orders o
on c.customer_id = o.customer_id
join order_items oi
on o.order_id = oi.order_id
join products p
on oi.product_id = p.product_id
group by c.customer_name
having sum(p.price * oi.quantity) >
(select avg(total_spending)from(select sum(p.price * oi.quantity) as total_spending
from orders o
join order_items oi
on o.order_id = oi.order_id
join products p
on oi.product_id = p.product_id
group by o.customer_id) as avg_table
);

-- Q29. Find products contributing more than 10% of company revenue.
select p.product_name,sum(p.price * oi.quantity) as revenue
from products p
join order_items oi
on p.product_id = oi.product_id
group by p.product_name
having sum(p.price * oi.quantity) >
(select sum(p2.price * oi2.quantity) * 0.10
    from products p2
    join order_items oi2
    on p2.product_id = oi2.product_id
);

-- Q30. Find the city generating the highest revenue.
select c.city,sum(p.price * oi.quantity) as revenue
from customers c
join orders o
on c.customer_id = o.customer_id
join order_items oi
on o.order_id = oi.order_id
join products p
on oi.product_id = p.product_id
group by c.city
order by revenue desc
limit 1;





 










